### ISSUE TITLE
Support walrus operator creating new variables + recursive lambda functions

### ISSUE THREAD

**Issue by sean-niemann** [berry-lang/berry#394]
The newly added walrus operator is a great addition to Berry, but it is not currently possible to create variables; the variables need to be pre-existing. The error message is rather cryptic as well.

```berry
print(n:=2) # syntax_error: string:1: try to assign constant expressions.
```

This could also be useful for creating recursive lambda functions without the need for using an existing variable. We currently need to declare the lambda function to something before assigning it to a function.

```berry
fn=0
fn=/n->n?1:fn(n+1)
```

It would be nice if the walrus operator could be used to create recurisve lambda functions like this

```berry
fn:=/n->n?1:fn(n+1)
```
Or simply plain assignment
```berry
fn=/n->n?1:fn(n+1)
```

**Comment by s-hadinger** [comment]
Lots of questions here.

First I tried to have an option where the walrus operator creates the variable on the fly, but it's not possible due to the nature of the single pass compiler of Berry. I can elaborate why, but in short, new variable declarations need to be before any statement, not in the middle.

Actually `print(n:=2)` does work in the REPL by accident. But
`def f() print(n:=2) end`
does print what I find is explicit enough
`syntax_error: stdin:1: strict: no global 'n', did you mean 'var n'?`

For recursive lambda, the fact that any variable must be known by the compiler before being used is in fact a good feature that saved be a ton of hidden bugs. But the drawback is that it requires to define it with a dummy value before. It is maybe possible to patch the compiler in this very specific case, but it will not patch the case of two recursive functions calling one another. This is again due to the single pass compiler that does not have a `linker` phase to check defined or not defined variables.

Last trick, if the function is global, you can use the `global` module to avoid the compilation error. But that's an edge case and wouldn't work inside a function (and performance wide it's not great because it adds an indirection):
```berry
import global
fn=/n->n?1:global.fn(n+1)
```
```
