### ISSUE TITLE
Is `index = 0` valid?

### ISSUE THREAD

**Issue by s-hadinger** [berry-lang/berry#73]
Hi,
I'm confused when using the following code:

```
// be_top == 0
be_loadstring(vm, "1+1");

// be_top == 1
// be_absindex(vm, 0) == 2
be_pcall(berry.vm, 0); 

// be_top == 1
const char *s = be_tostring(berry.vm, 0);
// s == "2"

be_pop(vm, 1);
// be_top == 0
```

I thought `index = 0` was forbidden yet this is the only way to run the code above. I'm confused.

The calls above seem to refer to arguments that are above the stack top and should be invalid?

**Comment by skiars** [comment]
Indeed, index cannot be `0`.

https://github.com/Skiars/berry/blob/7ca972782ed29aa3aa1bef540f22ef120a03f4f8/src/be_object.c#L44

`vm->top` is the next value of the top element of the stack, so `vm->top+0` is obviously an invalid index.

Your example should be just a coincidence, because VM will use some registers and release them after the function returns. You may use these released registers.
